language: ruby
install: ./mvnw initialize
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  include:
    - rvm: jruby
      jdk: openjdk6
      script: ./mvnw test
    - rvm: jruby
      jdk: openjdk7
      script: ./mvnw test
    - rvm: jruby
      jdk: oraclejdk7
      script: ./mvnw test
    - rvm: jruby
      jdk: oraclejdk8
      script: ./mvnw test
  allow_failures:
    - rvm: ruby-head
